import os
import subprocess

from modules.naming import unique_slug


ATTRIBUTION_COMMENT = (
    "Generated by twitch-highlights "
    "(https://github.com/NexRushVr/twitch-highlights)"
)


def _metadata_args(title: str | None = None, description: str | None = None) -> list[str]:
    """Build ffmpeg `-metadata` argv pairs. Always includes the tool attribution comment."""
    args = ["-metadata", f"comment={ATTRIBUTION_COMMENT}"]
    if title:
        args += ["-metadata", f"title={title}"]
    if description:
        args += ["-metadata", f"description={description}"]
    return args


def extract_clip(
    video_path: str,
    start: float,
    end: float,
    out_path: str,
    padding: float = 3.0,
    title: str | None = None,
    description: str | None = None,
    quiet: bool = False,
) -> str:
    actual_start = max(0.0, start - padding)
    actual_end = end + padding
    duration = actual_end - actual_start

    cmd = [
        "ffmpeg", "-y",
        "-ss", str(actual_start),
        "-i", video_path,
        "-t", str(duration),
        "-c:v", "libx264",
        "-crf", "18",
        "-c:a", "aac",
        *_metadata_args(title=title, description=description),
        out_path,
    ]
    kwargs = {"check": True}
    if quiet:
        kwargs["stdout"] = subprocess.DEVNULL
        kwargs["stderr"] = subprocess.PIPE
    subprocess.run(cmd, **kwargs)
    return out_path


def clip_name_prefix(config: dict, streamer: str | None = None) -> str:
    """Filename prefix for clips: the streamer/channel handle when we have one,
    else a generic fallback. Derives from config when `streamer` isn't passed."""
    s = (streamer or "").strip().lstrip("@")
    if not s:
        st = config.get("source_type")
        if st == "vodvod":
            s = config.get("vodvod_channel", "").lstrip("@")
        elif st == "kick":
            s = config.get("kick_channel", "").lstrip("@")
    return s or "highlight"


def batch_extract(video_path: str, clips: list, config: dict, progress=None,
                  streamer: str | None = None) -> list:
    os.makedirs(config["output_dir"], exist_ok=True)
    output_files = []
    quiet = not bool(config.get("verbose", False))

    # Clips are named "<streamer>-<adjective>-<noun>.mp4" (Docker-style), e.g.
    # "abehamm-sneaky-otter.mp4". The reason/score live in the manifest meta +
    # embedded mp4 metadata, so no info is lost — the fun slug just gives each
    # highlight a memorable, shareable identity that its captioned variant and
    # AVIF exports reuse.
    prefix = clip_name_prefix(config, streamer)
    used = set()

    iterable = enumerate(clips)
    if progress is not None:
        iterable = enumerate(progress.iter(clips, total=len(clips), desc="clips"))

    for i, clip in iterable:
        reason = clip.get("reason", "clip")
        slug = unique_slug(used)
        fname = f"{prefix}-{slug}.mp4"
        out = os.path.join(config["output_dir"], fname)
        extract_clip(
            video_path,
            clip["start"],
            clip["end"],
            out,
            config.get("clip_padding_seconds", 3.0),
            title=reason,
            description=clip.get("description") or None,
            quiet=quiet,
        )
        output_files.append({"file": out, "meta": clip})

    return output_files
